name = "bookingos"
main = "src/index.js"
compatibility_date = "2026-07-07"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = true

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "bookingos-db"
database_id = "86120cac-4bf0-4a76-8dea-eacd3287cd15"
migrations_dir = "migrations"
[vars]
PUBLIC_BASE_URL = "https://bookingos.fangwl591021.workers.dev"
DEFAULT_TENANT_ID = "demo-tenant"
MERCHANT_TENANT_SELECTION_TTL_SECONDS = "300"
MERCHANT_LIFF_IDENTITY_LOGIN_ENABLED = "true"
MERCHANT_LIFF_ID = "2010657278-FgmMUI2U"
CUSTOMER_SESSION_TTL_SECONDS = "604800"
CUSTOMER_LIFF_IDENTITY_LOGIN_ENABLED = "false"
CUSTOMER_LIFF_ID = "2010657278-9wbTln1T"
[[kv_namespaces]]
binding = "PUSH_KV"
id = "44f999c57822402198b9c68c03698699"
